#!/usr/bin/env bash
# Install nginx
apt-get -y install nginx

# Firewall: Allow Nginx to serve on HTTP
ufw allow 'Nginx HTTP'

# Override th index file served as home page
echo "Hello World!" >> /var/www/html/index.html

#Give the user  ownership to the website files
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# Redirect to /redirect_me  youtube
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=0HtEZOPwcN0 permanent;' /etc/nginx/sites-available/default

service nginx start
