#!/usr/bin/env bash
# Install setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 428524-web-01 52.87.153.215:80 check
   server 428524-web-02 100.27.13.53:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
